name: CI

on:
  push:
    branches:
      - master

env:
  RAILS_ENV: 'test'
  RAKE_ENV: 'test'
  NODE_ENV: 'test'

jobs:
  cucumber:
    name: Cucumber tests
    runs-on: ubuntu-latest

    env:
      TEST_WITH_POSTGRESQL: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Cucumber tests
      run: |
        bundle exec cucumber \
          --format json \
          --out cucumber-results.json

    - name: Zip results file
      if: always()
      run: |
        zip -r results.zip cucumber-results.json
      continue-on-error: true

    - name: Publish Cucumber report in Z4J
      if: always()
      run: |
        curl -X POST https://api.zephyrscale.smartbear.com/v2/automations/executions/cucumber\?projectKey\=MYC\&autoCreateTestCases\=true \
        -H "Authorization: Bearer ${{ secrets.ZSCALE_TOKEN }}" \
        -F "file=@results.zip"
        
      continue-on-error: true
